core/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_view
from .views import index, contact, signup
from .forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('signup/', signup, name='signup'),
    path('login/', auth_view.LoginView.as_view(template_name = 'core/login.html', authentication_form = LoginForm), name='login' ),
    #path('logout/', auth_view.LogoutView.as_view( http_method_names = ['get', 'post', 'options'], template_name='core/logout.html'),name='logout'),
   # path('logout/', logout_view, name='logout')
   path('logout/', auth_view.LogoutView.as_view(template_name='core/logout.html'), name='logout'),
]

puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('item/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('message/', include('conversations.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

item/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=150)
    class Meta:
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    description = models.TextField()
    price = models.FloatField()
    image = models.ImageField(default='default.jpg',upload_to='items_images')
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name
    

    

core/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

#sign up form
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    username = forms.CharField(widget = forms.TextInput(attrs = {
        'placeholder': 'Enter Username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    email = forms.CharField(widget = forms.EmailInput(attrs = {
        'placeholder': 'Enter your email',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    password1 = forms.CharField(widget = forms.PasswordInput(attrs = {
        'placeholder': 'Enter password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    password2 = forms.CharField(widget = forms.PasswordInput(attrs = {
        'placeholder': 'Confirm your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

#log in form

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget = forms.TextInput(attrs = {
        'placeholder': 'Enter Username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    password = forms.CharField(widget = forms.PasswordInput(attrs = {
        'placeholder': 'Enter your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

core/views.py
from django.shortcuts import render, redirect
from item.models import Item, Category
from .forms import SignUpForm, LoginForm
from django.contrib.auth import logout

def index(request):
    items = Item.objects.filter(is_sold=False)[:6]
    categories = Category.objects.all()
    context = {
        'items': items,
        'categories': categories,
    }
    return render(request, 'core/index.html', context)


def contact(request):
    return render(request, 'core/contact.html')

#sign up 
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = SignUpForm()
    return render(request, 'core/signup.html', {'form':form})

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <script src="https://cdn.tailwindcss.com"></script>
    <title> {% block title %}{% endblock  %} | Puddle </title>
      <style>
        form {
            display: inline;
        }
    </style>
</head>
<body>
    <!--Navbar section................................-->
    <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
        <a href="{% url 'index' %}" class="text-xl font-semibold">Puddle</a>

        <div class="space-x-6">
            <a href="{% url 'browse' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

            {% if request.user.is_authenticated %}
                <a href="{% url 'new-item' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
                <a href="{% url 'inbox' %}" class="px-6 py-3 text-lg font-semibold bg-sky-500 text-white rounded-xl hover:bg-sky-700">Inbox</a>
                <a href="{% url 'home' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Dashboard</a>
                {% comment %} <a href="{% url 'logout' %}" class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-800"> Log out
                </a> {% endcomment %}
                <form method="post" action="{% url 'logout' %}" class="block-element">
                  {% csrf_token %}
                  <button type="submit" class=" px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-800 bloi">Logout</button>
                </form>
                
                 
            {% else %}
                <a href="{% url 'signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
                <a href="{% url 'login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log In</a>
            {% endif %}
        </div>
    </nav>
    <!--End Navbar.............................................-->
    <div class="px-6 py-6">
        {% block content %}{% endblock  %}
    </div>

    <footer class="px-6 py-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font:semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Qui</p>
        </div>
        <div class="w-1/3">
            <h1 class="mb-5 font:semibold text-gray-400">Menu</h1>

            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>

                <li><a href="{% url 'contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>

                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy</a></li>

                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

core/templates/core/contact.html
{% extends "core/base.html" %}

{% block title %}Contact{% endblock  %}

{% block content %}
<h2>This is Contact page</h2>
{% endblock  %}

core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}Welcome{% endblock  %}

{% block content %}
<!-- items showing-->
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <div >
                <a href="{% url "item-detail" item.id %}">
                    <div> 
                        <img src="{{ item.image.url }}" alt="" class="rounded-t-xl">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl" > {{ item.name }} </h2>
                        <p class="text-gray-500">Price: {{item.price}} </p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>  

    <!--category showing -->
   <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div >
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl" > {{ category.name }} </h2>
                            <p class="text-gray-500">{{ category.item_set.count}} Items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>  


{% endblock  %}

core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %}Log In{% endblock  %}

{% block content %}

    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl ">
        <h1 class="mb-6 text-3xl text-center">Log In</h1>
        <hr>
        <form action="" method='post'>
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">LogIn</button>
        </form>
    </div>

{% endblock  %}

core/templates/core/logout.html
{% extends "core/base.html" %}
{% block content %}
{% csrf_token %}
    <div class="px-10 py-10 mx-auto text-center max-w-sm rounded overflow-hidden shadow-lg bg-red-200 mb-4">
        <h2>You have been logged out</h2>
    <div class="border-top pt-5 mb-4">
        <small class="text-muted">
            <a href="{% url 'login' %}" class="mt-8 px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-green-700" >Log In Again</a>
        </small>
    </div>
    </div>
{% endblock content %}

core/templates/core/signup.html
{% extends "core/base.html" %}

{% block title %}Sign Up{% endblock  %}

{% block content %}

    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl text-center">Sign Up</h1>
        <hr>

        <form action="" method='post'>
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1 }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Confirm Password</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>

{% endblock  %}